version: '3' 

services:
  kafka:
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
  
  web-socket-gateway:
    build: 
      context: BackendServices/WebSocketGateway
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - kafka
    restart: always
    env_file:
      - ./back.env
    
  auth-service:
    build: 
      context: BackendServices/AuthService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    env_file:
      - ./back.env

  message-service:
    build: 
      context: BackendServices/MessageService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./back.env
  front:
    build:
      context: Front/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./front.env

