version: '3' 

services:
  kafka:
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
  
  web-sockets-gateway:
    build: 
      context: BackendServices/WebSocketsHandler
      dockerfile: Dockerfile
    ports: 
      - "5001:5001"
    depends_on:
      - kafka
    restart: always
    
  auth-service:
    build: 
      context: BackendServices/AuthService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - kafka
