apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.backend.authentication.name }}-{{ .Values.version }}
  labels:
    app: {{ .Values.name }}-back-{{ .Values.version }}
    version: {{.Values.version}}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-back-{{ .Values.version }}
    version: {{ .Values.version }}

  ports:
  - name: http
    port: {{.Values.backend.authentication.port}}
    targetPort: {{.Values.backend.authentication.port}}