apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.messages.name }}-{{ .Values.version }}
  labels:
    app: {{.Values.backend.messages.name}}-{{ .Values.version }}
    version: {{.Values.version}}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.messages.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.messages.name }}-{{ .Values.version }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.messages.name }}-{{ .Values.version }}
        version: {{.Values.version}}
    spec:
      containers:
      - name: {{.Values.backend.messages.name}}-container
        image: bouaouinaziz/chat-app-message-service
        ports:
        - containerPort: {{ .Values.backend.messages.port }}
        env:
          - name: PRODUCTION
            value: "true"
          - name: MESSAGES_DB
            valueFrom:
                secretKeyRef:
                    name: {{ .Values.namespace }}-secret
                    key: db_conn
