apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: HOSTNAME_COMMAND
          value: "route -n | awk '/UG[ \t]/{print $$2}'"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
      volumes:
        - name: kafka-vol
          hostPath:
            path: /var/run/docker.sock
      restartPolicy: Always