apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka