apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper