apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-gateway
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.authentication.name }}-{{ .Values.version }}
            port:
              number: 5000
      - path: /messages
        pathType: Prefix
        backend:
            service:
                name: {{ .Values.backend.messages.name }}-service
                port:
                    number: 3001
      - path: /ws
        pathType: Prefix
        backend:
            service:
                name: {{ .Values.backend.gateway.name }}-service
                port:
                    number: 3000
    
        