apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: chat-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: chat-gateway
spec:
  gatewayClassName: chat-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: chat-route
spec:
  parentRefs:
  - name: chat-gateway
  hostnames:
  - "*"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80