apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-authentication
  labels:
    app: auth
spec:
  replicas: {{ .Values.authentication.deployment.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: bouaouinaziz/chat-app-auth-service:latest
        ports:
        - containerPort: {{ .Values.authentication.service.port }}
        env:
          - name: PRODUCTION
            value: "true"
          - name: SECRET_KEY
            value: {{ .Values.authentication.deployment.jwt }}