name: Building images & pushing to docker hub
on:
  push:
    tags:
      - "v*"
env:
  FRONT_SERVICE_LOCATION: "./Front"
  FRONT_IMAGE_NAME: "chat-app-front"
  AUTH_SERVICE_LOCATION: "./BackendServices/AuthService"
  AUTH_IMAGE_NAME: "chat-app-auth-service"
  MESSAGE_SERVICE_LOCATION: "./BackendServices/MessageService"
  MESSAGE_IMAGE_NAME: "chat-app-message-service"
  GATEWAY_SERVICE_LOCATION: "./BackendServices/WebSocketGateway"
  GATEWAY_IMAGE_NAME: "chat-app-gateway"
  
jobs:
  buildingImages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Logging in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Build & push Front
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.FRONT_SERVICE_LOCATION }}
          file: ${{ env.FRONT_SERVICE_LOCATION }}/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.FRONT_IMAGE_NAME}}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.FRONT_IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }}
      - name: Build & push Auth service
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.AUTH_SERVICE_LOCATION }}
          file: ${{ env.AUTH_SERVICE_LOCATION }}/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.AUTH_IMAGE_NAME}}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.AUTH_IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }}
      - name: Build & push Message service
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.MESSAGE_SERVICE_LOCATION }}
          file: ${{ env.MESSAGE_SERVICE_LOCATION }}/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.MESSAGE_IMAGE_NAME}}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.MESSAGE_IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }}
      - name: Build & push Gateway service
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.GATEWAY_SERVICE_LOCATION }}
          file: ${{ env.GATEWAY_SERVICE_LOCATION }}/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.GATEWAY_IMAGE_NAME}}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.GATEWAY_IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }}